
image: Visual Studio 2017

platform:
  - x64
  - ia32

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn
  - yarn prerelease

build_script:
  - yarn build
  - yarn pack
  - yarn release:win

test: off