
image: Visual Studio 2017

branches:
  only:
    - master

platform:
  - ia32

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64

build_script:
  - npm run release:win

test: off